### ISSUE TITLE
Feature request: Video ID

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-sonic-screwdriver#1]
Most of the time you are required to customise the embed code of a video, and so it would be extremely useful to be able to access just the video ID, so that custom embed code can be used in templates.

**Comment by johnkhughes** [comment]
[Boom](https://github.com/castlegateit/cgit-wp-sonic-screwdriver/commit/84e7186b1d0fc6afd6794d6a0bd391320095aafa)
